environment:
  properties:
    jdkPathPrefix: 'plugins/jreleaser/build/jdks'
    jdkFilePrefix: 'zulu17.32.13-ca-jdk17.0.2'

project:
  name: jreleaser
  description: Release projects quickly and easily with JReleaser
  longDescription: |
    JReleaser is a release automation tool. Its goal is to simplify creating releases and
    publishing artifacts to multiple package managers while providing customizable options.
    JReleaser takes inputs from popular builds tools (Ant, Maven, Gradle) such as JAR files,
    binary distributions (.zip, .tar), JLink images, or any other file that you’d like to
    publish as a Git release on popular Git services such as GitHub, GitLab, or Gitea.
    Distribution files may additionally be published to be consumed by popular package managers
    such as Homebrew, Chocolatey, Snapcraft, or get ready to be launched via JBang. Releases
    may be announced in a variety of channels such as Twitter, Zulip, SDKMAN!, and more.
  links:
    homepage: https://jreleaser.org
    faq: https://{{repoHost}}/{{repoOwner}}/{{repoName}}/discussions
    donation: https://opencollective.com/jreleaser
  authors:
    - Andres Almiray
  license: Apache-2.0
  inceptionYear: 2020
  stereotype: cli
  screenshots:
    - url: https://jreleaser.org/images/app-full-release-command.png
      caption: JReleaser in action
  icons:
    - url: https://raw.githubusercontent.com/jreleaser/jreleaser/main/src/media/icon_256x256.png
      width: 256
      height: 256
  java:
    groupId: org.jreleaser
    version: 8
    multiProject: true
  tags:
    - 'jreleaser'
    - 'release'
    - 'tool'
    - 'java'
    - 'git'

platform:
  replacements:
    aarch_64: aarch64

release:
  github:
    overwrite: true
    sign: true
    discussionCategoryName: Announcements
    changelog:
      formatted: ALWAYS
      preset: conventional-commits
      format: '- {{commitShortHash}} {{commitTitle}}'
      contributors:
        format: '- {{contributorName}}{{#contributorUsernameAsLink}} ({{.}}){{/contributorUsernameAsLink}}'
      contentTemplate: 'src/jreleaser/changelog.tpl'
      labelers:
        - label: 'i18n'
          title: 'regex:^(?:i18n(?:\(.*\))?!?):\s.*'
          order: 120
        - label: 'dependencies'
          title: 'regex:^(?:deps(?:\(.*\))?!?):\s.*'
          order: 130
        - label: 'allcontributors1'
          title: 'regex:^docs: update .all-contributorsrc.*'
          order: -1
        - label: 'allcontributors2'
          title: 'regex:^docs: update CONTRIBUTORS.md.*'
          order: -2
      categories:
        - title: '🌐 Translation'
          key: 'i18n'
          order: 70
          labels:
            - 'i18n'
        - title: '⚙️  Dependencies'
          key: 'dependencies'
          order: 80
          labels:
            - 'dependencies'
        - title: 'allcontributors'
          order: 59
          labels:
            - 'allcontributors1'
            - 'allcontributors2'
      hide:
        categories:
          - 'merge'
          - 'allcontributors'
        contributors:
          - 'GitHub'
          - 'allcontributors'
      replacers:
        - search: 'i18n: '
        - search: 'deps: '

signing:
  active: always
  armored: true
  files: false

checksum:
  files: false

announce:
  twitter:
    active: release
    status: 🚀 JReleaser {{projectVersion}} has been released! {{releaseNotesUrl}}

assemble:
  archive:
    jreleaser-archive:
      active: always
      attachPlatform: true
      formats: [ZIP, TAR, TAR_BZ2, TAR_GZ, TAR_XZ, TBZ2, TGZ, TXZ]
      fileSets:
        - input: '.'
          includes: [ 'VERSION' ]

  jlink:
    jreleaser-standalone:
      active: always
      java:
        version: 11
        mainClass: org.jreleaser.cli.Main
      imageName: '{{distributionName}}-{{projectEffectiveVersion}}'
      executable: jreleaser
      jdeps:
        multiRelease: base
        ignoreMissingDeps: true
      additionalModuleNames:
        - 'java.security.sasl'
        - 'java.security.jgss'
        - 'jdk.crypto.cryptoki'
        - 'jdk.crypto.ec'
        - 'jdk.localedata'
        - 'jdk.net'
        - 'jdk.security.auth'
        - 'jdk.security.jgss'
      targetJdks:
        - path: '{{jdkPathPrefix}}/zulu17Osx/{{jdkFilePrefix}}-macosx_x64/zulu-17.jdk/Contents/Home'
          platform: 'osx-x86_64'
        - path: '{{jdkPathPrefix}}/zulu17OsxArm/{{jdkFilePrefix}}-macosx_aarch64/zulu-17.jdk/Contents/Home'
          platform: 'osx-aarch_64'
        - path: '{{jdkPathPrefix}}/zulu17Linux/{{jdkFilePrefix}}-linux_x64'
          platform: 'linux-x86_64'
        - path: '{{jdkPathPrefix}}/zulu17LinuxArm/{{jdkFilePrefix}}-linux_aarch64'
          platform: 'linux-aarch_64'
        - path: '{{jdkPathPrefix}}/zulu17LinuxMusl/{{jdkFilePrefix}}-linux_musl_x64'
          platform: 'linux_musl-x86_64'
        - path: '{{jdkPathPrefix}}/zulu17LinuxMuslArm/{{jdkFilePrefix}}-linux_musl_aarch64'
          platform: 'linux_musl-aarch_64'
        - path: '{{jdkPathPrefix}}/zulu17Windows/{{jdkFilePrefix}}-win_x64'
          platform: 'windows-x86_64'
        - path: '{{jdkPathPrefix}}/zulu17WindowsArm/{{jdkFilePrefix}}-win_aarch64'
          platform: 'windows-aarch_64'
      mainJar:
        path: 'plugins/jreleaser/build/libs/jreleaser-{{projectVersion}}.jar'
      jars:
        - pattern: 'plugins/jreleaser/build/dependencies/flat/*.jar'

distributions:
  jreleaser:
    java:
      mainClass: org.jreleaser.cli.Main
    flatpak:
      active: always
      componentId: org.jreleaser.cli
      developerName: JReleaser
      runtime: freedesktop
      runtimeVersion: 21.08
      finishArgs:
        - --share=network
        - --filesystem=host
      categories:
        - Developer Tools
      repository:
        active: release
        owner: flathub
        name: org.jreleaser.cli
    chocolatey:
      active: always
      remoteBuild: true
      title: JReleaser
      iconUrl: 'https://rawcdn.githack.com/jreleaser/jreleaser/0934fa1fa3f0bd09c0c8c39fbdeb5df2ce507457/src/media/icon_128x128.png'
      bucket:
        active: release
    jbang:
      active: always
    macports:
      active: always
      categories:
        - devel
        - java
      maintainers:
        - '@aalmiray'
      repository:
        active: release
        name: jreleaser-macports
    scoop:
      active: always
      bucket:
        active: release
    sdkman:
      active: release
    snap:
      active: always
      remoteBuild: true
      base: core18
      architectures:
        - buildOn: [ amd64, arm64 ]
      plugs:
        - name: dot-config-files
          attributes:
            interface: personal-files
          writes:
            - $HOME/.jreleaser
          reads:
            - $HOME/.gnupg
            - $HOME/.gitconfig
            - $HOME/.config/jgit
      localPlugs:
        - network
        - home
        - dot-config-files
    spec:
      active: always
      repository:
        active: release
        name: jreleaser-copr
    artifacts:
      - path: plugins/{{distributionName}}/build/distributions/{{distributionName}}-{{projectVersion}}.zip
        transform: '{{distributionName}}/{{distributionName}}-{{projectEffectiveVersion}}.zip'
        extraProperties:
          skipSpec: true
      - path: plugins/{{distributionName}}/build/distributions/{{distributionName}}-{{projectVersion}}.tar
        transform: '{{distributionName}}/{{distributionName}}-{{projectEffectiveVersion}}.tar'
        extraProperties:
          skipFlatpak: true

  jreleaser-ant-tasks:
    artifacts:
      - path: plugins/{{distributionName}}/build/distributions/{{distributionName}}-{{projectVersion}}.zip
        transform: '{{distributionName}}/{{distributionName}}-{{projectEffectiveVersion}}.zip'

  jreleaser-tool-provider:
    type: SINGLE_JAR
    artifacts:
      - path: plugins/{{distributionName}}/build/libs/{{distributionName}}-{{projectVersion}}.jar
        transform: '{{distributionName}}/{{distributionName}}-{{projectEffectiveVersion}}.jar'

  jreleaser-standalone:
    appImage:
      active: always
      componentId: org.jreleaser.cli
      developerName: JReleaser
      categories:
        - Development
      repository:
        active: release
        name: jreleaser-appimage
    brew:
      active: always
      formulaName: jreleaser
      multiPlatform: true
      tap:
        active: release
        commitMessage: 'jreleaser {{tagName}}'
    docker:
      active: always
      repository:
        active: always
        commitMessage: 'jreleaser {{tagName}}'
      registries:
        - serverName: DEFAULT
          username: jreleaser
      labels:
        'org.opencontainers.image.title': 'jreleaser'
      postCommands:
        - 'VOLUME /workspace'
      specs:
        slim:
          imageNames:
            - 'jreleaser/jreleaser-{{dockerSpecName}}:{{tagName}}'
            - 'jreleaser/jreleaser-{{dockerSpecName}}:latest'
          matchers:
            platform: 'linux-x86_64'
          preCommands:
            - 'ARG DEBIAN_FRONTEND=noninteractive'
            - 'ENV TZ=Europe/Zurich'
            - 'RUN apt-get update && apt-get install -y unzip binutils fakeroot rpm'
        alpine:
          imageNames:
            - 'jreleaser/jreleaser-{{dockerSpecName}}:{{tagName}}'
            - 'jreleaser/jreleaser-{{dockerSpecName}}:latest'
          matchers:
            platform: 'linux_musl-x86_64'
          preCommands:
            - 'RUN apk add unzip binutils fakeroot rpm bash'

files:
  artifacts:
    - path: VERSION

upload:
  s3:
    jreleaser:
      active: always